/*
OPERADORES DE COMPARAÇÃO
> MAIOR QUE
>= MAIOR OU IGUAL A
< MENOR QUE
<= MENOR OU IGUAL A
== IGUALDADE (VALOR)
=== IGUALDADE RESTRITA (VALOR E TIPO) (só usar esse)
!= DIFERENTE
!== DIFERENTE RESTRITA (só usar esse)
*/
console.log(10 > 5);
